# Generated by Django 3.2.7 on 2021-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
